export default [
  { name: 'Login', params: ['Username', 'Secret'] },
  { name: 'CoreShowChannels', params: [] },
  { name: 'Ping', params: [] },
  { name: 'Hangup', params: [] },
  { name: 'CoreStatus', params: [] },
  { name: 'Status', params: [] },
  { name: 'DahdiShowChannels', params: [] },
  { name: 'CoreSettings', params: [] },
  { name: 'ListCommands', params: [] },
  { name: 'Logoff', params: [] },
  { name: 'AbsoluteTimeout', params: [] },
  { name: 'SipShowPeer', params: [] },
  { name: 'SipShowRegistry', params: [] },
  { name: 'SipQualifyPeer', params: [] },
  { name: 'SIPPeers', params: [] },
  { name: 'IAXPeers', params: [] },
  { name: 'AgentLogoff', params: [] },
  { name: 'Agents', params: [] },
  { name: 'AttendedTransfer', params: [] },
  { name: 'ChangeMonitor', params: [] },
  { name: 'Command', params: [] },
  { name: 'CreateConfig', params: [] },
  { name: 'DbDel', params: [] },
  { name: 'DbDeltree', params: [] },
  { name: 'DbGet', params: [] },
  { name: 'DbPut', params: [] },
  { name: 'ExtensionState', params: [] },
  { name: 'GetConfig', params: ['Filename'] },
  { name: 'GetConfigJson', params: ['Filename'] },
  { name: 'GetVar', params: [] },
  { name: 'JabberSend', params: [] },
  { name: 'ListCategories', params: [] },
  { name: 'PauseMonitor', params: [] },
  { name: 'UnpauseMonitor', params: [] },
  { name: 'StopMonitor', params: [] },
  { name: 'LocalOptimizeAway', params: [] },
  { name: 'SetVar', params: [] },
  { name: 'Reload', params: [] },
  { name: 'PlayDtmf', params: [] },
  { name: 'Park', params: [] },
  { name: 'ParkedCalls', params: [] },
  { name: 'Monitor', params: ['format', 'mix'], defaults: { format: 'wav', mix: true } },
  { name: 'ModuleCheck', params: [] },
  { name: 'ModuleLoad', params: ['LoadType'], defaults: { LoadType: 'Load' } },
  { name: 'ModuleUnload', params: ['LoadType'], defaults: { LoadType: 'Unload' } },
  { name: 'ModuleReload', params: ['LoadType'], defaults: { LoadType: 'record' } },
  { name: 'MailboxCount', params: [] },
  { name: 'MailboxStatus', params: [] },
  { name: 'VoicemailUsersList', params: [] },
  { name: 'Redirect', params: [] },
  { name: 'Bridge', params: [] },
  { name: 'ShowDialPlan', params: [] },
  { name: 'SendText', params: [] },
  { name: 'Queues', params: [] },
  { name: 'QueuePause', params: ['Interface', 'Paused', 'Queue', 'Reason'], optional: ['Queue', 'Reason'], defaults: { Paused: true } },
  { name: 'QueueSummary', params: [] },
  { name: 'QueueRule', params: [] },
  { name: 'QueueStatus', params: [] },
  { name: 'QueueReset', params: [] },
  { name: 'QueueRemove', params: ['Interface', 'Queue'] },
  { name: 'Originate', params: [] },
  { name: 'QueueAdd', params: ['Interface', 'Queue'] },
  { name: 'QueueLog', params: [] },
  { name: 'MeetmeList', params: ['Conference'], optional: ['Conference'] },
  { name: 'MeetmeMute', params: ['Meetme', 'Usernum'] },
  { name: 'MeetmeUnmute', params: ['Meetme', 'Usernum'] },
  { name: 'ConfbridgeListRooms', params: [] },
  { name: 'ConfbridgeList', params: ['Conference'] },
  { name: 'ConfbridgeKick', params: ['Conference', 'Channel'] },
  { name: 'ConfbridgeLock', params: ['Conference'] },
  { name: 'ConfbridgeUnlock', params: ['Conference'] },
  { name: 'ConfbridgeMute', params: ['Conference', 'Channel'] },
  { name: 'ConfbridgeUnmute', params: ['Conference', 'Channel'] },
  { name: 'AGI', params: ['Channel', 'Command', 'CommandId'] },
  { name: 'BlindTransfer', params: ['Channel', 'Context', 'Extension'] },
  { name: 'SIPpeerstatus' },
  { name: 'BridgeList' },
  { name: 'BridgeInfo' }
];
