export default [
  { name: 'AGI', params: ['Channel', 'Command', 'CommandId'] },
  { name: 'AbsoluteTimeout', params: [] },
  { name: 'AgentLogoff', params: [] },
  { name: 'Agents', params: [] },
  { name: 'Atxfer', params: ['Channel', 'Context', 'Extension'] },
  { name: 'BlindTransfer', params: ['Channel', 'Context', 'Extension'] },
  { name: 'Bridge', params: [] },
  { name: 'BridgeDestroy', params: [] },
  { name: 'BridgeInfo', params: [] },
  { name: 'BridgeKick', params: [] },
  { name: 'BridgeList', params: [] },
  { name: 'ChangeMonitor', params: [] },
  { name: 'Command', params: [] },
  { name: 'ConfbridgeKick', params: ['Conference', 'Channel'] },
  { name: 'ConfbridgeList', params: ['Conference'] },
  { name: 'ConfbridgeListRooms', params: [] },
  { name: 'ConfbridgeLock', params: ['Conference'] },
  { name: 'ConfbridgeMute', params: ['Conference', 'Channel'] },
  { name: 'ConfbridgeUnmute', params: ['Conference', 'Channel'] },
  { name: 'ConfbridgeUnlock', params: ['Conference'] },
  { name: 'CoreSettings', params: [] },
  { name: 'CoreShowChannels', params: [] },
  { name: 'CoreStatus', params: [] },
  { name: 'CreateConfig', params: [] },
  { name: 'DbDel', params: [] },
  { name: 'DbDeltree', params: [] },
  { name: 'DbGet', params: [] },
  { name: 'DbGetTree', params: [] },
  { name: 'DbPut', params: [] },
  { name: 'DeviceStateList', params: [] },
  { name: 'ExtensionState', params: [] },
  { name: 'ExtensionStateList', params: [] },
  { name: 'GetConfig', params: ['Filename'] },
  { name: 'GetConfigJSON', params: ['Filename'] },
  { name: 'GetVar', params: [] },
  { name: 'Hangup', params: ['Channel'] },
  { name: 'IAXPeers', params: [] },
  { name: 'IAXPeerslist', params: [] },
  { name: 'IAXRegistry', params: [] },
  { name: 'JabberSend', params: [] },
  { name: 'ListCategories', params: [] },
  { name: 'ListCommands', params: [] },
  { name: 'LocalOptimizeAway', params: [] },
  { name: 'Login', params: ['Username', 'Secret'] },
  { name: 'Logoff', params: [] },
  { name: 'MailboxCount', params: [] },
  { name: 'MailboxStatus', params: [] },
  { name: 'MeetmeList', params: ['Conference'], optional: ['Conference'] },
  { name: 'MeetmeMute', params: ['Meetme', 'Usernum'] },
  { name: 'MeetmeUnmute', params: ['Meetme', 'Usernum'] },
  { name: 'ModuleCheck', params: [] },
  { name: 'ModuleLoad', params: ['LoadType'], defaults: { LoadType: 'Load' } },
  { name: 'ModuleReload', params: ['LoadType'], defaults: { LoadType: 'record' } },
  { name: 'ModuleUnload', params: ['LoadType'], defaults: { LoadType: 'Unload' } },
  { name: 'Monitor', params: ['format', 'mix'], defaults: { format: 'wav', mix: true } },
  { name: 'Originate', params: [] },
  { name: 'Park', params: [] },
  { name: 'ParkedCalls', params: [] },
  { name: 'PauseMonitor', params: [] },
  { name: 'Ping', params: [] },
  { name: 'PJSIPHangup', params: [] },
  { name: 'PJSIPNotify', params: [] },
  { name: 'PJSIPQualify', params: [] },
  { name: 'PJSIPRegister', params: [] },
  { name: 'PJSIPShowAors', params: [] },
  { name: 'PJSIPShowAuths', params: [] },
  { name: 'PJSIPShowContacts', params: [] },
  { name: 'PJSIPShowEndpoint', params: [] },
  { name: 'PJSIPShowEndpoints', params: [] },
  { name: 'PJSIPShowRegistrationInboundContactStatuses', params: [] },
  { name: 'PJSIPShowRegistrationsInbound', params: [] },
  { name: 'PJSIPShowRegistrationsOutbound', params: [] },
  { name: 'PJSIPShowResourceLists', params: [] },
  { name: 'PJSIPShowSubscriptionsInbound', params: [] },
  { name: 'PJSIPShowSubscriptionsOutbound', params: [] },
  { name: 'PJSIPUnregister', params: [] },
  { name: 'PlayDTMF', params: [] },
  { name: 'PresenceState', params: [] },
  { name: 'PresenceStateList', params: [] },
  { name: 'QueueAdd', params: ['Interface', 'Queue'] },
  { name: 'QueueLog', params: [] },
  {
    name: 'QueuePause',
    params: ['Interface', 'Paused', 'Queue', 'Reason'],
    optional: ['Queue', 'Reason'],
    defaults: { Paused: true },
  },
  { name: 'QueueRemove', params: ['Interface', 'Queue'] },
  { name: 'QueueReset', params: [] },
  { name: 'QueueRule', params: [] },
  { name: 'QueueStatus', params: [] },
  { name: 'QueueSummary', params: [] },
  { name: 'Queues', params: [] },
  { name: 'Redirect', params: [] },
  { name: 'Reload', params: [] },
  { name: 'SIPPeers', params: [] },
  { name: 'SIPpeerstatus' },
  { name: 'SendText', params: [] },
  { name: 'SetVar', params: [] },
  { name: 'ShowDialPlan', params: [] },
  { name: 'SipQualifyPeer', params: [] },
  { name: 'SipShowPeer', params: [] },
  { name: 'SipShowRegistry', params: [] },
  { name: 'Status', params: [] },
  { name: 'StopMixMonitor', params: [] },
  { name: 'StopMonitor', params: [] },
  { name: 'UnpauseMonitor', params: [] },
  { name: 'UpdateConfig', params: [] },
  { name: 'VoicemailUsersStatus', params: [] },
  { name: 'VoicemailUsersList', params: [] },
];
